name: update rss
on: 
  schedule:
    - cron:  '*/15 * * * *'
  push:
    branches: 
    -  master 
         
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
      
    - name: set up python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: update rss
      run: 
        python update.py
        
    - name: commit
      run: |
        git config --global user.email NUAARSS@github.com
        git config --global user.name NUAARSS
        git add .
        git commit -m "update rss" -a
        
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
